name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Every Sunday at 0AM UTC
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  Pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Install and Run Pytest
        run: |
          export SETUPTOOLS_USE_DISTUTILS=stdlib
          pip3 install pytest
          python3 -m pytest -s
